"""add relationships_extracted_at to filing_sections

Revision ID: 10917446bf8c
Revises: b62a560f5c8d
Create Date: 2026-04-15 18:59:10.522209
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '10917446bf8c'
down_revision: Union[str, None] = 'b62a560f5c8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filing_sections', sa.Column('relationships_extracted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('filing_sections', 'relationships_extracted_at')
    # ### end Alembic commands ###
