"""add counterparty_aliases and resolved_to columns

Revision ID: 1e48a3f6aabc
Revises: 10917446bf8c
Create Date: 2026-04-15 19:24:17.317630
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1e48a3f6aabc'
down_revision: Union[str, None] = '10917446bf8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counterparty_aliases',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('alias_name', sa.String(length=256), nullable=False),
    sa.Column('alias_normalized', sa.String(length=256), nullable=False),
    sa.Column('canonical_cik', sa.String(length=16), nullable=False),
    sa.Column('canonical_ticker', sa.String(length=16), nullable=True),
    sa.Column('canonical_name', sa.String(length=256), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_counterparty_aliases_alias_normalized'), 'counterparty_aliases', ['alias_normalized'], unique=True)
    op.create_index('ix_counterparty_aliases_canonical_cik', 'counterparty_aliases', ['canonical_cik'], unique=False)
    op.create_index(op.f('ix_counterparty_aliases_canonical_ticker'), 'counterparty_aliases', ['canonical_ticker'], unique=False)
    op.add_column('relationships', sa.Column('resolved_to_cik', sa.String(length=16), nullable=True))
    op.add_column('relationships', sa.Column('resolved_to_ticker', sa.String(length=16), nullable=True))
    op.create_index(op.f('ix_relationships_resolved_to_cik'), 'relationships', ['resolved_to_cik'], unique=False)
    op.create_index(op.f('ix_relationships_resolved_to_ticker'), 'relationships', ['resolved_to_ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_relationships_resolved_to_ticker'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_resolved_to_cik'), table_name='relationships')
    op.drop_column('relationships', 'resolved_to_ticker')
    op.drop_column('relationships', 'resolved_to_cik')
    op.drop_index(op.f('ix_counterparty_aliases_canonical_ticker'), table_name='counterparty_aliases')
    op.drop_index('ix_counterparty_aliases_canonical_cik', table_name='counterparty_aliases')
    op.drop_index(op.f('ix_counterparty_aliases_alias_normalized'), table_name='counterparty_aliases')
    op.drop_table('counterparty_aliases')
    # ### end Alembic commands ###
