"""workspace_runs table

Revision ID: 28aa0887373a
Revises: 524c7aed3d24
Create Date: 2026-05-09 15:46:43.736010
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '28aa0887373a'
down_revision: Union[str, None] = '524c7aed3d24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_runs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('parent_research_run_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('ticker_model_version_before', sa.Integer(), nullable=False),
    sa.Column('ticker_model_version_after', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('verdict', sa.String(length=1024), nullable=True),
    sa.Column('step_outputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_research_run_id'], ['research_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_runs_ticker'), 'workspace_runs', ['ticker'], unique=False)
    op.create_index(
        'ix_workspace_runs_ticker_created',
        'workspace_runs',
        ['ticker', sa.text('created_at DESC')],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_workspace_runs_ticker_created', table_name='workspace_runs')
    op.drop_index(op.f('ix_workspace_runs_ticker'), table_name='workspace_runs')
    op.drop_table('workspace_runs')
    # ### end Alembic commands ###
