"""create ticker_models

Revision ID: 8b80bfb7f1dc
Revises: 2db2e8812418
Create Date: 2026-05-06 14:26:45.199835
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '8b80bfb7f1dc'
down_revision: Union[str, None] = '2db2e8812418'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticker_models',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parent_research_run_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_research_run_id'], ['research_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'version', name='uq_ticker_models_ticker_version')
    )
    op.create_index(op.f('ix_ticker_models_ticker'), 'ticker_models', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticker_models_ticker'), table_name='ticker_models')
    op.drop_table('ticker_models')
    # ### end Alembic commands ###
