"""initial_schema

Revision ID: 8eebd8f4659a
Revises: 
Create Date: 2026-04-11 03:15:22.459671
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '8eebd8f4659a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('themes',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_theme_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('seed_tickers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('screener_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('x_search_terms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('signal_weights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_theme_id'], ['themes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_themes_parent_theme_id'), 'themes', ['parent_theme_id'], unique=False)
    op.create_table('research_runs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('theme_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('phase', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('loop_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_runs_theme_id'), 'research_runs', ['theme_id'], unique=False)
    op.create_index(op.f('ix_research_runs_ticker'), 'research_runs', ['ticker'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('theme_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('signal_type', sa.String(length=32), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_theme_id'), 'signals', ['theme_id'], unique=False)
    op.create_index(op.f('ix_signals_ticker'), 'signals', ['ticker'], unique=False)
    op.create_table('surprise_alerts',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('theme_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('prior_velocity_ratio', sa.Float(), nullable=False),
    sa.Column('current_velocity_ratio', sa.Float(), nullable=False),
    sa.Column('fired_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_surprise_alerts_theme_id'), 'surprise_alerts', ['theme_id'], unique=False)
    op.create_index(op.f('ix_surprise_alerts_ticker'), 'surprise_alerts', ['ticker'], unique=False)
    op.create_table('citations',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('run_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('metric', sa.String(length=256), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('source_name', sa.String(length=256), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citations_run_id'), 'citations', ['run_id'], unique=False)
    op.create_table('watchlist',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('theme_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('trigger_condition', sa.Text(), nullable=True),
    sa.Column('run_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], ),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlist_theme_id'), 'watchlist', ['theme_id'], unique=False)
    op.create_index(op.f('ix_watchlist_ticker'), 'watchlist', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_ticker'), table_name='watchlist')
    op.drop_index(op.f('ix_watchlist_theme_id'), table_name='watchlist')
    op.drop_table('watchlist')
    op.drop_index(op.f('ix_citations_run_id'), table_name='citations')
    op.drop_table('citations')
    op.drop_index(op.f('ix_surprise_alerts_ticker'), table_name='surprise_alerts')
    op.drop_index(op.f('ix_surprise_alerts_theme_id'), table_name='surprise_alerts')
    op.drop_table('surprise_alerts')
    op.drop_index(op.f('ix_signals_ticker'), table_name='signals')
    op.drop_index(op.f('ix_signals_theme_id'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_research_runs_ticker'), table_name='research_runs')
    op.drop_index(op.f('ix_research_runs_theme_id'), table_name='research_runs')
    op.drop_table('research_runs')
    op.drop_index(op.f('ix_themes_parent_theme_id'), table_name='themes')
    op.drop_table('themes')
    # ### end Alembic commands ###
