"""add relationships

Revision ID: b62a560f5c8d
Revises: f3e1dc0d6911
Create Date: 2026-04-15 18:42:58.115228
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b62a560f5c8d'
down_revision: Union[str, None] = 'f3e1dc0d6911'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relationships',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('filing_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('section_key', sa.String(length=64), nullable=False),
    sa.Column('counterparty_name', sa.String(length=256), nullable=False),
    sa.Column('relationship_type', sa.String(length=32), nullable=False),
    sa.Column('magnitude_pct', sa.Numeric(), nullable=True),
    sa.Column('unnamed', sa.Boolean(), nullable=False),
    sa.Column('verbatim_quote', sa.Text(), nullable=True),
    sa.Column('confirmed_bilateral', sa.Boolean(), nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filing_id', 'section_key', 'counterparty_name', 'relationship_type', name='uq_relationships_filing_section_counterparty_type')
    )
    op.create_index(op.f('ix_relationships_counterparty_name'), 'relationships', ['counterparty_name'], unique=False)
    op.create_index(op.f('ix_relationships_filing_id'), 'relationships', ['filing_id'], unique=False)
    op.create_index(op.f('ix_relationships_ticker'), 'relationships', ['ticker'], unique=False)
    op.create_index('ix_relationships_ticker_type', 'relationships', ['ticker', 'relationship_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_relationships_ticker_type', table_name='relationships')
    op.drop_index(op.f('ix_relationships_ticker'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_filing_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_counterparty_name'), table_name='relationships')
    op.drop_table('relationships')
    # ### end Alembic commands ###
