"""add filings and xbrl_facts

Revision ID: d14ab77781f8
Revises: 8eebd8f4659a
Create Date: 2026-04-14 17:54:15.945741
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd14ab77781f8'
down_revision: Union[str, None] = '8eebd8f4659a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filings',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('accession_number', sa.String(length=32), nullable=False),
    sa.Column('cik', sa.String(length=16), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('form_type', sa.String(length=16), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=False),
    sa.Column('period_of_report', sa.Date(), nullable=True),
    sa.Column('primary_document_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filings_accession_number'), 'filings', ['accession_number'], unique=True)
    op.create_index(op.f('ix_filings_cik'), 'filings', ['cik'], unique=False)
    op.create_index(op.f('ix_filings_ticker'), 'filings', ['ticker'], unique=False)
    op.create_index('ix_filings_ticker_form', 'filings', ['ticker', 'form_type'], unique=False)
    op.create_table('xbrl_facts',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('filing_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('concept', sa.String(length=128), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('fiscal_period', sa.String(length=8), nullable=True),
    sa.Column('value', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xbrl_facts_concept'), 'xbrl_facts', ['concept'], unique=False)
    op.create_index('ix_xbrl_facts_concept_period', 'xbrl_facts', ['concept', 'period_end'], unique=False)
    op.create_index(op.f('ix_xbrl_facts_filing_id'), 'xbrl_facts', ['filing_id'], unique=False)
    op.create_index(op.f('ix_xbrl_facts_ticker'), 'xbrl_facts', ['ticker'], unique=False)
    op.create_index('ix_xbrl_facts_ticker_concept', 'xbrl_facts', ['ticker', 'concept'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_xbrl_facts_ticker_concept', table_name='xbrl_facts')
    op.drop_index(op.f('ix_xbrl_facts_ticker'), table_name='xbrl_facts')
    op.drop_index(op.f('ix_xbrl_facts_filing_id'), table_name='xbrl_facts')
    op.drop_index('ix_xbrl_facts_concept_period', table_name='xbrl_facts')
    op.drop_index(op.f('ix_xbrl_facts_concept'), table_name='xbrl_facts')
    op.drop_table('xbrl_facts')
    op.drop_index('ix_filings_ticker_form', table_name='filings')
    op.drop_index(op.f('ix_filings_ticker'), table_name='filings')
    op.drop_index(op.f('ix_filings_cik'), table_name='filings')
    op.drop_index(op.f('ix_filings_accession_number'), table_name='filings')
    op.drop_table('filings')
    # ### end Alembic commands ###
