"""add questions table

Revision ID: e68b9478e450
Revises: 771650442ce6
Create Date: 2026-05-05 22:03:51.478972
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e68b9478e450'
down_revision: Union[str, None] = '771650442ce6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('theme_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('auto_answerable', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('answer_source', sa.String(length=32), nullable=True),
    sa.Column('created_run_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('resolved_run_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dismiss_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_run_id'], ['research_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_run_id'], ['research_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_questions_status_priority', 'questions', ['status', 'priority'], unique=False)
    op.create_index('idx_questions_ticker_status', 'questions', ['ticker', 'status'], unique=False)
    op.create_index('idx_questions_ticker_theme_status', 'questions', ['ticker', 'theme_id', 'status'], unique=False)
    op.create_index(op.f('ix_questions_ticker'), 'questions', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questions_ticker'), table_name='questions')
    op.drop_index('idx_questions_ticker_theme_status', table_name='questions')
    op.drop_index('idx_questions_ticker_status', table_name='questions')
    op.drop_index('idx_questions_status_priority', table_name='questions')
    op.drop_table('questions')
    # ### end Alembic commands ###
