"""add filing_sections

Revision ID: f3e1dc0d6911
Revises: d14ab77781f8
Create Date: 2026-04-15 09:01:53.231132
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f3e1dc0d6911'
down_revision: Union[str, None] = 'd14ab77781f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filing_sections',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('filing_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('section_key', sa.String(length=64), nullable=False),
    sa.Column('heading', sa.String(length=512), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('extraction_method', sa.String(length=16), nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filing_id', 'section_key', name='uq_filing_sections_filing_section')
    )
    op.create_index(op.f('ix_filing_sections_filing_id'), 'filing_sections', ['filing_id'], unique=False)
    op.create_index(op.f('ix_filing_sections_section_key'), 'filing_sections', ['section_key'], unique=False)
    op.create_index(op.f('ix_filing_sections_ticker'), 'filing_sections', ['ticker'], unique=False)
    op.create_index('ix_filing_sections_ticker_section', 'filing_sections', ['ticker', 'section_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_filing_sections_ticker_section', table_name='filing_sections')
    op.drop_index(op.f('ix_filing_sections_ticker'), table_name='filing_sections')
    op.drop_index(op.f('ix_filing_sections_section_key'), table_name='filing_sections')
    op.drop_index(op.f('ix_filing_sections_filing_id'), table_name='filing_sections')
    op.drop_table('filing_sections')
    # ### end Alembic commands ###
